FROM mysql:latest

VOLUME [ "./conf.d:/etc/mysql/conf.d:ro" ]

ENV MYSQL_ROOT_PASSWORD=
ENV MYSQL_ALLOW_EMPTY_PASSWORD=true
ENV MYSQL_USER=petclinic
ENV MYSQL_PASSWORD=petclinic
ENV MYSQL_DATABASE=petclinic

EXPOSE 3306